/**
 * Generates specs/README.md from the frontmatter defined by
 * specs/008-spec-metadata.md. Run via `pnpm spec:index`.
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

export const SPECS_DIR = 'specs';
export const ADR_DIR = 'docs/adr';
export const TEST_DIR = 'test';
export const CONSTITUTION = '000-constitution.md';
export const INDEX_PATH = join(SPECS_DIR, 'README.md');

export const STATUSES = ['standing', 'specified', 'implemented', 'superseded'] as const;
export const KEYS = [
  'status',
  'implemented',
  'pr',
  'superseded_by',
  'constitution',
  'adr',
] as const;

export type Frontmatter = Record<string, string>;

export interface Spec {
  file: string;
  title: string;
  meta: Frontmatter | null;
}

const BANNER = '<!-- Generated by `pnpm spec:index`. Do not edit by hand. -->';
const EMPTY = '—';

/** Parses the narrow frontmatter dialect 008 permits: `key: value`, no nesting. */
export function parseFrontmatter(source: string): Frontmatter | null {
  if (!source.startsWith('---\n')) return null;
  const end = source.indexOf('\n---\n', 3);
  if (end === -1) return null;

  const meta: Frontmatter = {};
  for (const line of source.slice(4, end).split('\n')) {
    if (line.trim() === '') continue;
    const at = line.indexOf(':');
    if (at === -1) return null;
    meta[line.slice(0, at).trim()] = line
      .slice(at + 1)
      .replace(/\s#.*$/, '')
      .trim();
  }
  return meta;
}

/** Reads a `[a, b]` value. Absent is empty; 008 permits no other list syntax. */
export function listOf(meta: Frontmatter | null, key: string): string[] {
  const raw = meta?.[key];
  if (raw === undefined) return [];
  const inner = raw.trim().replace(/^\[/, '').replace(/\]$/, '');
  return inner
    .split(',')
    .map(entry => entry.trim())
    .filter(entry => entry !== '');
}

export function specFiles(): string[] {
  return readdirSync(SPECS_DIR)
    .filter(name => /^\d{3}-[a-z0-9-]+\.md$/.test(name))
    .sort();
}

/** Maps each ADR number to its filename, so links resolve rather than guess. */
export function adrFiles(): Map<string, string> {
  const found = new Map<string, string>();
  for (const name of readdirSync(ADR_DIR)) {
    const match = name.match(/^(\d{4})-[a-z0-9-]+\.md$/);
    if (match?.[1]) found.set(match[1], name);
  }
  return found;
}

/** Clause identifiers that actually have a heading in the constitution. */
export function constitutionClauses(): Set<string> {
  const source = readFileSync(join(SPECS_DIR, CONSTITUTION), 'utf8');
  return new Set([...source.matchAll(/^## (C\d+)\./gm)].flatMap(m => (m[1] ? [m[1]] : [])));
}

/**
 * Test files citing each spec number, keyed by the three-digit number. This is
 * derived on every run rather than declared, because a list of enforcing tests
 * typed into frontmatter is stale the first time a test is renamed.
 */
export function citationsByNumber(): Map<string, string[]> {
  const found = new Map<string, string[]>();
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith('.ts')) {
        const numbers = new Set(
          [...readFileSync(path, 'utf8').matchAll(/specs\/(\d{3})/g)].flatMap(m =>
            m[1] ? [m[1]] : [],
          ),
        );
        for (const number of numbers) found.set(number, [...(found.get(number) ?? []), path]);
      }
    }
  };
  walk(TEST_DIR);
  return found;
}

export function readSpecs(): Spec[] {
  return specFiles().map(file => {
    const source = readFileSync(join(SPECS_DIR, file), 'utf8');
    const title = source.match(/^# (.+)$/m)?.[1]?.trim();
    return { file, title: title ?? file, meta: parseFrontmatter(source) };
  });
}

/**
 * Pads cells the way Prettier formats markdown tables, so `format:check` passes.
 * The floor of 3 is Prettier's: a delimiter cell is never narrower than `---`.
 */
function table(header: string[], rows: string[][]): string {
  const widths = header.map((cell, i) =>
    Math.max(3, cell.length, ...rows.map(row => row[i]?.length ?? 0)),
  );
  const line = (cells: string[]): string =>
    `| ${cells.map((cell, i) => cell.padEnd(widths[i] ?? 0)).join(' | ')} |`;

  return [
    line(header),
    `| ${widths.map(width => '-'.repeat(width)).join(' | ')} |`,
    ...rows.map(line),
  ].join('\n');
}

export function renderIndex(
  specs: Spec[] = readSpecs(),
  citations: Map<string, string[]> = citationsByNumber(),
  adrs_ = adrFiles(),
): string {
  const rows = specs.map(({ file, title, meta }) => {
    const tests = citations.get(file.slice(0, 3))?.length ?? 0;
    const clauses = listOf(meta, 'constitution');
    const adrs = listOf(meta, 'adr');
    return [
      `[${title}](${file})`,
      meta?.status ?? EMPTY,
      meta?.implemented ?? EMPTY,
      meta?.pr ? `#${meta.pr}` : EMPTY,
      tests > 0 ? String(tests) : EMPTY,
      clauses.length > 0 ? clauses.join(', ') : EMPTY,
      adrs.length > 0 ? adrs.map(n => `[${n}]`).join(', ') : EMPTY,
    ];
  });

  const referenced = [...new Set(specs.flatMap(spec => listOf(spec.meta, 'adr')))].sort();

  return [
    BANNER,
    '',
    '# Specs',
    '',
    'What each status claims, and the evidence it requires, is defined in',
    '[008-spec-metadata.md](008-spec-metadata.md). `specified` means the behaviour',
    'described is **not** in the code yet.',
    '',
    '**Tests** counts the files under `test/` citing the spec, and is derived on',
    'every run rather than declared. A spec marked `implemented` with no citing',
    'test fails the suite.',
    '',
    table(['Spec', 'Status', 'Implemented', 'PR', 'Tests', 'Constitution', 'ADRs'], rows),
    '',
    // Shortcut reference definitions: the ADR column stays narrow and clickable.
    ...referenced.map(n => `[${n}]: ../${ADR_DIR}/${adrs_.get(n) ?? ''}`),
    '',
  ].join('\n');
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  writeFileSync(INDEX_PATH, renderIndex());
  console.log(`wrote ${INDEX_PATH}`);
}
